lr: 0.001
lr_f: 0.001
num_hidden: 1024
num_heads: 4
num_out_heads: 1
num_layers: 4
weight_decay: 0.05
weight_decay_f: 0
max_epoch: 10 
max_epoch_f: 1000
batch_size: 512
batch_size_f: 256
mask_rate: 0.5
num_layers: 4
encoder: gat
decoder: gat 
activation: prelu
attn_drop: 0.2
linear_prob: True
in_drop: 0.2
loss_fn: sce 
drop_edge_rate: 0.5
optimizer: adamw
alpha_l: 2
scheduler: True
remask_method: random
momentum: 0.996
lam: 10.0
delayed_ema_epoch: 0
num_remasking: 3