lr: 0.005
lr_f: 0.025
num_hidden: 512
num_heads: 2
num_out_heads: 1
num_layers: 2
weight_decay: 1e-5
weight_decay_f: 5e-4
max_epoch: 2000 
max_epoch_f: 500
mask_rate: 0.9
num_layers: 2
encoder: gat
decoder: gat 
activation: prelu
attn_drop: 0.1
linear_prob: True
in_drop: 0.2
loss_fn: sce 
drop_edge_rate: 0.0
optimizer: adam
replace_rate: 0.0
alpha_l: 4
scheduler: True
remask_method: fixed
momentum: 0.995
lam: 1
